<a href="https://colab.research.google.com/github/RifkieNurdianAdiNugroho/PCVK_Genap_2022/blob/master/challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Kode program menggunakan Matriks
import numpy as np

matriksA = np.array([[2,3],
                     [6,3]])
matriksB = np.array([[6,3],
                     [8,10]])
matriksC = np.array([[2,3],
                     [6,3]])  

perkalian_biasa = matriksA*matriksB*matriksC
perkalian_matriks1 = np.dot(matriksA,matriksB,matriksC)
perkalian_matriks2 = matriksA.dot(matriksB)
perkalian_matriks3 = matriksB.dot(matriksC)

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

print("Perkalian Biasa Matriks : ")
print(perkalian_biasa)

print("Perkalian Matriks Cara 1 : ")
print(perkalian_matriks1)

print("Perkalian Matriks Cara 2 : ")
print(perkalian_matriks2)

print("Perkalian Matriks Cara 3 : ")
print(perkalian_matriks3)

Matriks A :
[[2 3]
 [6 3]]
Matriks B :
[[ 6  3]
 [ 8 10]]
Perkalian Biasa Matriks : 
[[ 24  27]
 [288  90]]
Perkalian Matriks Cara 1 : 
[[36 36]
 [60 48]]
Perkalian Matriks Cara 2 : 
[[36 36]
 [60 48]]
Perkalian Matriks Cara 3 : 
[[396 360]
 [888 768]]
