<a href="https://colab.research.google.com/github/RifkieNurdianAdiNugroho/PCVK_Genap_2022/blob/master/challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Kode program menggunakan Matriks
import numpy as np
matriksA = np.array([[1,6,3],
                     [1,4,6],
                     [3,5,7]])
matriksB = np.array([[1,2,2],
                     [5,4,4],
                     [8,10,11]]) 

perkalian_skalar = matriksA*matriksB

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

perkalian_matriks = np.dot(matriksA,matriksB)

print("Perkalian Matriks : ")
print(perkalian_matriks)

Matriks A :
[[1 6 3]
 [1 4 6]
 [3 5 7]]
Matriks B :
[[ 1  2  2]
 [ 5  4  4]
 [ 8 10 11]]
Perkalian Matriks : 
[[ 55  56  59]
 [ 69  78  84]
 [ 84  96 103]]


Sumber belajar dari:https://ihzarizkyk.blogspot.com/2020/05/belajar-numpy-python-perkalian-matriks.html::

In [ ]:
#Kode Program menggunakan Matriks Skalar
matriksA = np.array([[1,2,4],
                     [2,5,6],
                     [3,4,1]])
matriksB = np.array([[2,2,1],
                     [3,1,2],
                     [4,2,1]]) 

perkalian_skalar = matriksA*matriksB

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

print("Perkalian Skalar Matriks : ")
print(perkalian_skalar)

Matriks A :
[[1 2 4]
 [2 5 6]
 [3 4 1]]
Matriks B :
[[2 2 1]
 [3 1 2]
 [4 2 1]]
Perkalian Skalar Matriks : 
[[ 2  4  4]
 [ 6  5 12]
 [12  8  1]]


In [3]:
from google.colab import drive
drive.mount('/content/drive')

import matplotlib.image as image
import numpy as np
img=image.imread('/content/drive/MyDrive/kitten01.jpg')#membaca image dan melakukan image processing menggunakan import image.imread
print("Matriks : ")
print(img)#pemanggilan variabel img yang telah melalui image processing

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Matriks : 
[[[ 53 105   0]
  [ 53 105   0]
  [ 53 104   0]
  ...
  [ 43  85   3]
  [ 42  81   2]
  [ 41  79   2]]

 [[ 57 106   0]
  [ 57 106   0]
  [ 55 106   1]
  ...
  [ 44  86   4]
  [ 44  83   4]
  [ 42  80   3]]

 [[ 59 108   1]
  [ 58 107   2]
  [ 56 107   2]
  ...
  [ 46  88   6]
  [ 45  84   5]
  [ 43  81   4]]

 ...

 [[104 170  80]
  [ 90 156  59]
  [ 46 108   1]
  ...
  [ 71 127  18]
  [ 71 127  16]
  [ 74 130  19]]

 [[ 77 143  53]
  [ 69 135  38]
  [ 52 114   7]
  ...
  [ 62 118   9]
  [ 63 119  10]
  [ 66 122  11]]

 [[ 50 116  26]
  [ 43 109  12]
  [ 50 112   5]
  ...
  [ 53 109   2]
  [ 55 111   2]
  [ 59 115   6]]]


Sumber Belajar dari:https://kopiding.in/membuat-matriks-pada-python/ & https://codepolitan.com/melakukan-operasi-matriks-di-python/