<a href="https://colab.research.google.com/github/RifkieNurdianAdiNugroho/PCVK_Genap_2022/blob/master/challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Kode program menggunakan Matriks
import numpy as np
matriksA = np.array([[1,6,3],
                     [1,4,6],
                     [3,5,7]])
matriksB = np.array([[1,2,2],
                     [5,4,4],
                     [8,10,11]]) 

perkalian_skalar = matriksA*matriksB

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

perkalian_matriks = np.dot(matriksA,matriksB)

print("Perkalian Matriks : ")
print(perkalian_matriks)

Matriks A :
[[1 6 3]
 [1 4 6]
 [3 5 7]]
Matriks B :
[[ 1  2  2]
 [ 5  4  4]
 [ 8 10 11]]
Perkalian Matriks : 
[[ 55  56  59]
 [ 69  78  84]
 [ 84  96 103]]


Sumber belajar dari:https://ihzarizkyk.blogspot.com/2020/05/belajar-numpy-python-perkalian-matriks.html::

In [ ]:
#Kode Program menggunakan Matriks Skalar
matriksA = np.array([[1,2,4],
                     [2,5,6],
                     [3,4,1]])
matriksB = np.array([[2,2,1],
                     [3,1,2],
                     [4,2,1]]) 

perkalian_skalar = matriksA*matriksB

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

print("Perkalian Skalar Matriks : ")
print(perkalian_skalar)

Matriks A :
[[1 2 4]
 [2 5 6]
 [3 4 1]]
Matriks B :
[[2 2 1]
 [3 1 2]
 [4 2 1]]
Perkalian Skalar Matriks : 
[[ 2  4  4]
 [ 6  5 12]
 [12  8  1]]


In [2]:
from google.colab import drive
drive.mount('/content/drive')

import matplotlib.image as image
import numpy as np
img=image.imread('/content/drive/MyDrive/lily.jpg')
print("Matriks : ")
print(img)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Matriks : 
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


Sumber Belajar dari:https://kopiding.in/membuat-matriks-pada-python/ & https://codepolitan.com/melakukan-operasi-matriks-di-python/